import streamlit as st
import pandas as pd
import plotly.express as px
import joblib
from sklearn.metrics import mean_absolute_error
from PIL import Image

st.set_page_config(
    page_title="SIR OTP Intelligence Dashboard",
    layout="wide"
)

st.title("Staten Island Railway OTP Intelligence Dashboard")
st.write(
    "An explainable machine learning dashboard for analyzing and forecasting "
    "On-Time Performance using MTA Open Data."
)

df = pd.read_csv("outputs/predictions/staten_island_otp_features.csv")
df["Month"] = pd.to_datetime(df["Month"])
model = joblib.load("models/xgboost_otp_model.pkl")

shap_image = Image.open("outputs/figures/shap_summary.png")

st.sidebar.header("Dashboard Filters")

day_time_options = df["Day Time"].unique()

selected_day_times = st.sidebar.multiselect(
    "Select Day Time",
    options=day_time_options,
    default=day_time_options
)

filtered_df = df[df["Day Time"].isin(selected_day_times)]
df_encoded = pd.get_dummies(
    filtered_df.copy(),
    columns=["Day Time", "Season"],
    drop_first=True
)

expected_cols = model.get_booster().feature_names

for col in expected_cols:
    if col not in df_encoded.columns:
        df_encoded[col] = 0

X_dashboard = df_encoded[expected_cols]

filtered_df = filtered_df.copy()
filtered_df["Predicted_OTP"] = model.predict(X_dashboard)

avg_otp = filtered_df["On-Time Performance"].mean()
avg_delay_rate = filtered_df["Delay_Rate"].mean()
best_otp = filtered_df["On-Time Performance"].max()
worst_otp = filtered_df["On-Time Performance"].min()

col1, col2, col3, col4 = st.columns(4)

col1.metric("Average OTP", f"{avg_otp:.2%}")
col2.metric("Average Delay Rate", f"{avg_delay_rate:.2%}")
col3.metric("Best OTP", f"{best_otp:.2%}")
col4.metric("Worst OTP", f"{worst_otp:.2%}")

st.subheader("OTP Trend Over Time")

fig = px.line(
    filtered_df,
    x="Month",
    y="On-Time Performance",
    color="Day Time",
    title="On-Time Performance Trend by Day Time"
)

st.plotly_chart(fig, use_container_width=True)

selected_prediction_group = st.selectbox(
    "Select Day Time for Prediction View",
    options=filtered_df["Day Time"].unique()
)

prediction_df = filtered_df[
    filtered_df["Day Time"] == selected_prediction_group
]
st.subheader("Actual vs Predicted OTP")

forecast_fig = px.line(
    prediction_df,
    x="Month",
    y=["On-Time Performance", "Predicted_OTP"],
    title=f"Actual vs Predicted OTP - {selected_prediction_group}"
)

st.plotly_chart(forecast_fig, use_container_width=True)
st.divider()
st.subheader("AI Explainability & Operational Drivers")

st.write(
    """
    SHAP (SHapley Additive Explanations) identifies which operational variables
    most influence OTP predictions generated by the XGBoost forecasting model.
    """
)

st.image(
    shap_image,
    caption="Global Feature Importance using SHAP",
    width=600
)
st.info(
    """
    Key operational drivers identified by the XGBoost forecasting model include:
    seasonality, delay rate, and recent OTP momentum.
    """
)